default:
  image: harbor.net/docker-base-images/maven:3.8.5-jdk-17-slim
  services:
    - name: harbor.net/hub-mirror/selenium/standalone-chrome:105.0
      alias: chrome
  tags:
    - autoscaling_uat
  artifacts:
    when: always
    expire_in: 2 week
    paths:
      - target/allure-results/
      - target/allure-report/

stages:
  - TestesFuncionais
  - Report

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  TZ: "America/Sao_Paulo"
  ALLURE_VERSION: "2.25.0"
  ALLURE_DIR: "$CI_PROJECT_DIR/allureUnzip/allure-$ALLURE_VERSION"
  ALLURE_BIN: "$ALLURE_DIR/bin"
  ALLURE_REPORT_DIR: "$CI_PROJECT_DIR/target/allure-report"
  ALLURE_RESULTS_DIR: "$CI_PROJECT_DIR/target/allure-results"
  ALLURE_COMMANDLINE_ZIP: "allure-commandline-$ALLURE_VERSION.zip"
  ALLURE_COMMANDLINE_DIR: "$CI_PROJECT_DIR/.m2/repository/io/qameta/allure/allure-commandline/$ALLURE_VERSION"

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .m2/repository/

TestesFuncionais-hom:
  stage: TestesFuncionais
  script:
    - mvn clean test -Pdev -Denv=dev -Dcustom:Plataforma=Chrome -Dselenide.remote=http://chrome:4444/wd/hub
    - ls -la target/allure-results/

Report:
  stage: Report
  when: always
  artifacts:
    name: allure-report-${CI_JOB_STARTED_AT}
    paths:
      - target/allure-results/
      - target/allure-report/
    reports:
      dotenv: build.env
  script:
    - echo "URL_PIPELINE_REPORT=/artifacts/download" >> build.env
    - cp $CI_PROJECT_DIR/src/test/resources/allure.properties $ALLURE_RESULTS_DIR
    - cp $CI_PROJECT_DIR/src/test/resources/environment.properties $ALLURE_RESULTS_DIR
    - cp $CI_PROJECT_DIR/src/test/resources/executor.json $ALLURE_RESULTS_DIR
    - mkdir -p $ALLURE_REPORT_DIR
    - echo $ALLURE_COMMANDLINE_DIR
    - apt-get update && apt-get install -y wget unzip
    - wget https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/$ALLURE_VERSION/$ALLURE_COMMANDLINE_ZIP -P $CI_PROJECT_DIR/.m2/repository/io/qameta/allure/allure-commandline/$ALLURE_VERSION/
    - unzip $CI_PROJECT_DIR/.m2/repository/io/qameta/allure/allure-commandline/$ALLURE_VERSION/$ALLURE_COMMANDLINE_ZIP -d $CI_PROJECT_DIR/allureUnzip
    - $ALLURE_BIN/allure generate --single-file $ALLURE_RESULTS_DIR -c -o $ALLURE_REPORT_DIR || true
